# Generated by Django 2.0.8 on 2018-10-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180913_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=80),
        ),
    ]
